[workspace]
members = ["canisters/eth_usdc_price", "logics/eth_usdc_price", "canisters/white_eth_0_01_pool_fees", "logics/white_eth_0_01_pool_fees", "canisters/white_eth_0_01_tcumul_28x6hr", "logics/white_eth_0_01_tcumul_28x6hr", "canisters/white_eth_0_01_v3pool", "logics/white_eth_0_01_v3pool", "canisters/white_eth_0_01_relayer", "logics/white_eth_0_01_relayer", "canisters/white_eth_0_01_indexer", "logics/white_eth_0_01_indexer", "canisters/white_eth_0_01_indexer_lens", "logics/white_eth_0_01_indexer_lens", "canisters/shared_algorithm_lens", "logics/shared_algorithm_lens", "canisters/wsteth_eth_0_01_pool_fees", "logics/wsteth_eth_0_01_pool_fees", "canisters/wsteth_eth_0_01_tcumul_28x6hr", "logics/wsteth_eth_0_01_tcumul_28x6hr", "canisters/wsteth_eth_0_01_v3pool", "logics/wsteth_eth_0_01_v3pool", "canisters/wsteth_eth_0_01_relayer", "logics/wsteth_eth_0_01_relayer", "canisters/wsteth_eth_0_01_indexer", "logics/wsteth_eth_0_01_indexer", "canisters/wsteth_eth_0_01_indexer_lens", "logics/wsteth_eth_0_01_indexer_lens", "canisters/rpl_eth_0_3_pool_fees", "logics/rpl_eth_0_3_pool_fees", "canisters/rpl_eth_0_3_tcumul_28x6hr", "logics/rpl_eth_0_3_tcumul_28x6hr", "canisters/rpl_eth_0_3_v3pool", "logics/rpl_eth_0_3_v3pool", "canisters/rpl_eth_0_3_relayer", "logics/rpl_eth_0_3_relayer", "canisters/rpl_eth_0_3_indexer", "logics/rpl_eth_0_3_indexer", "canisters/rpl_eth_0_3_indexer_lens", "logics/rpl_eth_0_3_indexer_lens", "canisters/dai_eth_0_3_pool_fees", "logics/dai_eth_0_3_pool_fees", "canisters/dai_eth_0_3_tcumul_28x6hr", "logics/dai_eth_0_3_tcumul_28x6hr", "canisters/dai_eth_0_3_v3pool", "logics/dai_eth_0_3_v3pool", "canisters/dai_eth_0_3_relayer", "logics/dai_eth_0_3_relayer", "canisters/dai_eth_0_3_indexer", "logics/dai_eth_0_3_indexer", "canisters/dai_eth_0_3_indexer_lens", "logics/dai_eth_0_3_indexer_lens", "bindings/*", "accessors/*"]

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
candid = "0.9.6"
ic-cdk = "0.11.3"
ic-cdk-macros = "0.8.1"
ic-cdk-timers = "0.5.0"
ic-stable-structures = "0.5.5"
serde = "1.0.163"
serde_bytes = "0.11.12"
serde_json = "1.0.108"
hex = "0.4.3"

ic-web3-rs = "0.1.3"
ic-solidity-bindgen = "0.1.9"
chainsight-cdk-macros = { git = "https://github.com/horizonx-tech/chainsight-sdk.git", rev = "6e55b5e8a38d1d853f4217614555f7ec7eaeb92b" }
chainsight-cdk = { git = "https://github.com/horizonx-tech/chainsight-sdk.git", rev = "6e55b5e8a38d1d853f4217614555f7ec7eaeb92b" }
