version: v1
label: price_usdc
components:
- component_path: components/chainlink_usdcusd.yaml
- component_path: components/lens_usdcusd.yaml
- component_path: components/relayer_oasyshub_testnet.yaml
