version: v1
label: crypto_volatility_index
components:
- component_path: components/snapshot_cvi_latest_round.yaml
- component_path: components/lens_cvi_scaler.yaml
- component_path: components/cvi_relayer.yaml
