version: v1
label: price_wbtc
components:
- component_path: components/chainlink_btcusd.yaml
- component_path: components/chainlink_wbtcbtc.yaml
- component_path: components/lens_wbtcusd.yaml
- component_path: components/relayer_oasyshub_testnet.yaml
- component_path: components/relayer_scroll_sepolia.yaml
