version: v1
label: uniswap_edpr
components:
- component_path: components/eth_usdc_price.yaml
- component_path: components/rndr_eth_1_pool_fees.yaml
- component_path: components/rndr_eth_1_tcumul_28x6hr.yaml
- component_path: components/rndr_eth_1_v3pool.yaml
- component_path: components/rndr_eth_1_relayer.yaml
- component_path: components/rndr_eth_1_indexer.yaml
- component_path: components/rndr_eth_1_indexer_lens.yaml
- component_path: components/shared_algorithm_lens.yaml
- component_path: components/usdc_eth_0_3_pool_fees.yaml
- component_path: components/usdc_eth_0_3_tcumul_28x6hr.yaml
- component_path: components/usdc_eth_0_3_v3pool.yaml
- component_path: components/usdc_eth_0_3_relayer.yaml
- component_path: components/usdc_eth_0_3_indexer.yaml
- component_path: components/usdc_eth_0_3_indexer_lens.yaml
- component_path: components/vra_eth_0_3_pool_fees.yaml
- component_path: components/vra_eth_0_3_tcumul_28x6hr.yaml
- component_path: components/vra_eth_0_3_v3pool.yaml
- component_path: components/vra_eth_0_3_relayer.yaml
- component_path: components/vra_eth_0_3_indexer.yaml
- component_path: components/vra_eth_0_3_indexer_lens.yaml
- component_path: components/wbtc_eth_0_05_pool_fees.yaml
- component_path: components/wbtc_eth_0_05_tcumul_28x6hr.yaml
- component_path: components/wbtc_eth_0_05_v3pool.yaml
- component_path: components/wbtc_eth_0_05_relayer.yaml
- component_path: components/wbtc_eth_0_05_indexer.yaml
- component_path: components/wbtc_eth_0_05_indexer_lens.yaml
