version: v1
label: uniswap_edpr
components:
- component_path: components/eth_usdc_price.yaml
- component_path: components/dai_eth_0_3_pool_fees.yaml
- component_path: components/dai_eth_0_3_tcumul_28x6hr.yaml
- component_path: components/dai_eth_0_3_v3pool.yaml
- component_path: components/shared_algorithm_lens.yaml
- component_path: components/dai_eth_0_3_indexer.yaml
- component_path: components/dai_eth_0_3_indexer_lens.yaml
- component_path: components/dai_eth_0_3_relayer.yaml
- component_path: components/shib_eth_1_pool_fees.yaml
- component_path: components/shib_eth_1_tcumul_28x6hr.yaml
- component_path: components/shib_eth_1_v3pool.yaml
- component_path: components/shib_eth_1_indexer.yaml
- component_path: components/shib_eth_1_indexer_lens.yaml
- component_path: components/shib_eth_1_relayer.yaml
- component_path: components/wsteth_eth_0_01_pool_fees.yaml
- component_path: components/wsteth_eth_0_01_tcumul_28x6hr.yaml
- component_path: components/wsteth_eth_0_01_v3pool.yaml
- component_path: components/wsteth_eth_0_01_indexer.yaml
- component_path: components/wsteth_eth_0_01_indexer_lens.yaml
- component_path: components/wsteth_eth_0_01_relayer.yaml
- component_path: components/rpl_eth_0_3_pool_fees.yaml
- component_path: components/rpl_eth_0_3_tcumul_28x6hr.yaml
- component_path: components/rpl_eth_0_3_v3pool.yaml
- component_path: components/rpl_eth_0_3_indexer.yaml
- component_path: components/rpl_eth_0_3_indexer_lens.yaml
- component_path: components/rpl_eth_0_3_relayer.yaml
