version: v1
label: sp_global_reit
components:
- component_path: components/sp_global_reit_indexer_https.yaml
- component_path: components/sp_global_reit_uint256_lens.yaml
- component_path: components/sp_global_reit_relayer.yaml
