version: v1
label: chainsight_20
components:
  - component_path: components/market_indexer_coingecko.yaml
  #- component_path: components/index_lens.yaml
  #- component_path: components/index_indexer.yaml
  #- component_path: components/uint256_lens.yaml
  #- component_path: components/relayer_scroll_sepolia.yaml
