version: v1
label: price_wethusd
components:
- component_path: components/chainlink_ethusd.yaml
- component_path: components/lens_ethusd.yaml
- component_path: components/relayer_oasyshub_testnet.yaml
