name: Check by CLI
on: workflow_dispatch
jobs:
  generate_pj_root_matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v3
      - name: Generate list of directories
        id: set-matrix
        run: |
          FOLDERS=$(find . -type f -name ".chainsight"  -not \( -path './old/*' -o -path './oracle/*' \) -exec dirname {} \; | jq -R -s -c 'split("\n")[:-1]')
          echo "matrix={\"target\":$FOLDERS}" >> $GITHUB_OUTPUT
  check:
    needs: generate_pj_root_matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.generate_pj_root_matrix.outputs.matrix) }}
    steps:
      - name: Processing for each pull request
        run: echo ${{ matrix.target }}
